config/routes.rb
 ProjectMgr::Application.routes.draw do

  root :to => 'projects#index'

  match "/home" => "projects#index", :as => :home

  devise_for :users

  resources :users
  
  resources :projects do
    get 'all', :on => :collection

    resources :tasks, :shallow => true
  end

  resources :tasks

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks
  belongs_to :user

  validates_presence_of :name

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project

  def pretty_date

     self.completed_at #.strftime("%m/%d/%Y")

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :projects

 def is_admin?
    self.id == 1
 end

  ROLES = %w[user distributor_admin corporate_admin site_developer]

  def role_symbols
    [role.to_sym]
  end


  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_filter :authenticate_user!


  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.find_all_by_user_id(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end


  def all
    if !current_user.is_admin?
      redirect_to home_path()
      return
    end
    
    @projects = Project.all()

    respond_to do |format|
      format.html { render 'index'}
      format.xml  { render :xml => @projects }
    end
  end


  # GET /projects/1
  # GET /projects/1.xml
  def show

    edit()
    @edit_mode = false

    if flash[:error]
      return
    else
      respond_to do |format|
        format.html { render 'edit'}
        format.xml  { render :xml => @project }
      end
    end
  end

  # GET /projects/1/edit
  def edit
    if Project.exists?(params[:id])
      @project = Project.find(params[:id])
      if @project.user_id == current_user.id or current_user.is_admin?
       @tasks = Task.find_all_by_project_id(@project.id)
      else
        deny_request("You are not allowed to view the requested data.")
        return
      end
    else
        deny_request("Record not found.")
      return
    end
     @edit_mode = true

  end


  def deny_request(message)
    if !message.empty?
      flash[:error] = message
    end
    redirect_to home_path()
    
  end


  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new
    @edit_mode = true

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end


  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    @project.user_id = current_user.id;

    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_project_path(@project) }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to projects_path() }
        format.xml  { head :ok }
      else
        @edit_mode = true
        @tasks = Task.find_all_by_project_id(@project.id)
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  def new #_task_to_project
   
    begin
      @project = Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to home_path()
      return
    end

    @task = @project.tasks.new(:user_id => current_user.id)

    #@task = Task.new(:project_id => @project.id, :user_id => current_user.id)

    respond_to do |format|
      format.html { render("edit")}
    end
  end



#  def new #_task_to_project
#    @project = Project.find(params[:project_id])
#
#    @task = @project.tasks.create(:user_id => current_user.id)
#
#    redirect_to edit_project_task_path(@project, @task)
#  end


  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to edit_project_path(@task.project_id) }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to edit_project_path(@task.project_id) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_topmenu.erb
<div id="menubar">
  
  <ul id="menu">

  <li><%= link_to 'Home', home_path()%></li>
  <li><%= link_to 'View All', all_projects_path() unless !current_user || !current_user.is_admin?  %></li>


<% if current_user %>

  <li><%= link_to 'My Account', edit_user_registration_path() %></li>
  <li><%= link_to 'Sign Out', destroy_user_session_path() %></li>

<% else %>

    <li><%= link_to 'Sign In', new_user_session_path() %></li>

<% end %>

</ul>


<% if current_user %>

  USER_ID = <%= current_user.id %>
  EMAIL = <%= current_user.email %>
  USERNAME = <%= current_user.username %>

<% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Super Duper Project Manager in Rails 3</title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
	$('#dialog').dialog({width: 500, height: 300, autoOpen: false});

        <% if flash[:error] %>
          $('#dialog').dialog({title: 'ERROR:'});
          $('#flash-message').replaceWith('<%= flash[:error] %>');
          $('#dialog').dialog('open');
        <% end %>
});

</script>

</head>
<body>

<div id="dialog" style="border:black; border-width: 2px; background-color: white;" title="Example dialog">
	<p id="flash-message">Some text that you want to display to the user.</p>
</div>


<%= render :partial => "layouts/topmenu" %>


<% if flash[:notice] and false %>
  <div class="flash-notice">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<% if flash[:error] and false %>
  <div class="flash-error">
    <p><%= flash[:error] %></p>
  </div>
<% end %>


<div id="main">
  <%= yield %>
</div>


  
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <% if @edit_mode %>
    <div class="actions">
      <%= f.submit "Save" %>
    </div>
  <% end %>

  <% if @project.id != nil %>
    <div class="field">
      <label for="created_by"> Created by:  <%= @project.user.email %> - <%= @project.created_at %> </label>
    </div>
    <div class="field">
      <label for="updated_at"> Updated:  <%= @project.updated_at %> </label>
    </div>

 <% end %>


<% end %>

app/views/projects/edit.html.erb
<h1>Project Details</h1>

<%= render 'form' %>

<%= render :partial => 'tasks/list', :locals => {:tasks => @tasks, :project_id => @project.id} %>

<% if @project.id != nil && @edit_mode %>
  <%= link_to 'New Task', new_project_task_path(@project) %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% @projects.each do |project| %>

<div class="project-div">
  <div class="project-name">
    <%= link_to project.name, edit_project_path(project) %>
  </div>
  <div class="project-actions">
    <%= link_to 'Show', project %>
    <%= link_to 'Edit', edit_project_path(project) %>
    <%= link_to 'Delete', project, :confirm => 'Are you sure?', :method => :delete %>
  </div>
 </div>

<% end %>

<%= link_to 'New Project', new_project_path %>

app/views/projects/index_orig.html.erb
<h1>Projects</h1>

<div class="project-div">
  <div class="project-name">
      <%= project.name %>
  </div>
  <div class="project-actions">
    <%= link_to 'Show', project %>
    <%= link_to 'Edit', edit_project_path(project) %>
    <%= link_to 'Delete', project, :confirm => 'Are you sure?', :method => :delete %>
  </div>"
 </div>
<%= link_to 'New Project', new_project_path %>



<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.user_id %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Delete', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>User:</b>
  <%= @project.user_id %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>

  <%= f.hidden_field :project_id %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :estimated_hrs %><br />
    <%= f.text_field :estimated_hrs %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>


<script type="text/javascript">
$(document).ready(function() {
 $('#task_estimated_hrs').datepicker({ buttonImage: '/images/calendar.gif',
                                       showOn: "button",
                                       buttonImageOnly: true,
                                       numberOfMonths: [1, 3],
			showOtherMonths: true,
			selectOtherMonths: true
                                     });
});

</script>

app/views/tasks/_list.erb
<h3>Tasks</h3>
<hr />

<table>
  <tr>
    <th>Priority</th>
    <th>Description</th>
    <th>Est. Hrs</th>
    <th>Completed</th>
    <th>Status</th>
    <th>User</th>
    <th>Project</th>
  </tr>

<% if tasks.nil? or tasks.empty? %>
  <p> >>> No Tasks exist for this Project. </p>
<% else %>
  <% tasks.each do |task| %>
    <tr>
      <td><%=h task.priority %></td>
      <td><%=h task.description %></td>
      <td><%=h task.estimated_hrs %></td>
      <td><%=h task.pretty_date %></td>
      <td><%= check_box_tag "task[complete_at]", "1", task.completed_at, :disabled => true %></td>
      <td><%=h task.user_id %></td>
      <td><%=h task.project.name %></td>

      <%# <td><%= link_to 'View', task </td>%>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Delete', task, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Back to Project', edit_project_path(@task.project_id) %>

app/views/tasks/index.html.erb
<%= render :partial => 'list', :locals => {:tasks => @tasks} %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @task.project_id %>
</p>

<p>
  <b>User:</b>
  <%= @task.user_id %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Estimated hrs:</b>
  <%= @task.estimated_hrs %>
</p>



<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>